In [2]:
import numpy as np
# anaconda에  기본적으로 포함되어 설치된 라이브러리

In [ ]:
! conda list

In [8]:
# ndarray class로부터 객체를 생성한다.
a = np.array([_ for _ in range(10)])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# np.array()로 생성한 객체는 numpy.ndarray 타입을 갖는다
type(a)

numpy.ndarray

In [11]:
a.shape

(10,)

In [12]:
test = [_ for _ in range(10)]

In [13]:
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
test.extend([10, 11, 12])

In [16]:
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [17]:
len(test)

13

In [18]:
test.pop()

12

In [19]:
test.append("str입니다")

In [20]:
len(test)

13

In [21]:
test[0]

0

In [22]:
type(test[0])

int

In [23]:
test[-1]

'str입니다'

In [24]:
len(test)

13

In [25]:
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 'str입니다']

In [26]:
type(test[-1])

str

In [27]:
ar2 = np.array([0.1, 12, 50, 2, 3.14])
ar2

array([ 0.1 , 12.  , 50.  ,  2.  ,  3.14])

In [28]:
x = [0,1,-1,0]
y = [1,0,0,0]
x/y

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [29]:
xn = np.array(x)
yn = np.array(y)


In [30]:
xn

array([ 0,  1, -1,  0])

In [31]:
yn

array([1, 0, 0, 0])

In [32]:
xn/yn

C:\Users\user\AppData\Local\Temp\ipykernel_5396\2118190955.py:1: RuntimeWarning: divide by zero encountered in true_divide
  xn/yn
C:\Users\user\AppData\Local\Temp\ipykernel_5396\2118190955.py:1: RuntimeWarning: invalid value encountered in true_divide
  xn/yn


array([  0.,  inf, -inf,  nan])

In [33]:
a = [1,2,3]
b = [10,20,30]

In [34]:
2*a+b

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [35]:
an = np.array(a)
bn = np.array(b)

In [36]:
2*an+bn

array([12, 24, 36])

In [37]:
an == 2

# broadcast

array([False,  True, False])

In [38]:
bn < 20

array([ True, False, False])

In [39]:
bn < np.array([20,20,20])

array([ True, False, False])

In [40]:
True == 1

True

In [41]:
False == 0

True

In [43]:
(an == 2) & (bn > 10)

# &: numpy에서 and 처럼 쓰임, 여기서 and쓰면 오류남
# 괄호 없으면 우선순위 때문에 밀려서 오류남

array([False,  True, False])

In [44]:
x = np.array([[1,2,3],
              [4,5,6]])

In [45]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
x.shape # 2행 3열

(2, 3)

In [49]:
a1 = np.array([[10,20,30,40], [50,60,70,80]])
a1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [50]:
d = np.array([[[1, 2, 3, 4], 
               [5, 6, 7, 8], 
               [9, 10, 11, 12]],
              [[11, 12, 13, 14], 
               [15, 16, 17, 18], 
               [19, 20, 21, 22]]])

In [51]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [52]:
d.dtype

dtype('int32')

In [60]:
test = [[1, 2, 3, 4], [5, 6, 7, 8]]
t = np.array(test)
t[1, 1]

6

In [62]:
test = [[1, 2, 3, 4], [5, 6, 7, 8]]
test[1][1]

6

In [63]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
a.shape

(2, 3)

In [65]:
a.ndim

2

In [66]:
a[-1, 0]

3

In [67]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]] # a에서 1, 2, 3의 값을 가져오기

In [83]:
a[0][:3]

[1, 2, 3]

In [84]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
a[0, :]

array([0, 1, 2, 3])

In [86]:
a[:, 1]

array([1, 5])

In [87]:
a[1, 1:]

array([5, 6, 7])

In [88]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [89]:
a[0, :2]

array([0, 1])

In [90]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [91]:
m[1, 2]

7

In [92]:
m[2, -1]

14

In [96]:
m[1, 1:3]

array([6, 7])

In [98]:
m[1:3, 2]

array([ 7, 12])

In [100]:
m[0:2, 3:]

array([[3, 4],
       [8, 9]])

In [101]:
zeros = np.zeros(5)

In [102]:
zeros

array([0., 0., 0., 0., 0.])

In [103]:
zeros.dtype

dtype('float64')

In [104]:
c= np.zeros((5,2), dtype = "i")

In [105]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [106]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [108]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [109]:
test = np.array([10, 20, 22])

In [110]:
np.ones_like(test, dtype='f')

array([1., 1., 1.], dtype=float32)

In [111]:
np.zeros_like(test, dtype='U10')

array(['', '', ''], dtype='<U10')

In [112]:
g = np.empty((4, 3))
g

array([[1.19739228e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.06099790e-312, 8.84378473e+165],
       [4.11697827e+179, 1.46219215e+165, 1.39340164e+165],
       [2.54576915e-052, 6.59925309e-042, 7.26437229e-043]])

In [116]:
a1 = np.ones((2, 3))
b1 = np.zeros((3, 3))
print(a1)
print(b1)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [114]:
np.vstack([a1, b1])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.hstack([a1, b1])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [123]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [118]:
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))

In [120]:
np.dstack([c1, c2]).shape

(3, 4, 2)

In [121]:
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
c3 = np.empty((3, 4))

In [125]:
np.dstack([c1, c2, c3]).shape

(3, 4, 3)

In [126]:
np.dstack([c1, c2, c3])

array([[[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]]])

In [127]:
np.stack([c1, c2, c3])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [128]:
d1 = np.ones((4,5))
d2 = np.zeros((4, 5))
d3 = np.arange(20).reshape(4, 5)

In [129]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [130]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [134]:
np.stack([d1, d2, d3],  axis = 1)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [136]:
np.stack([d1, d2, d3],  axis = 2).shape

(4, 5, 3)

In [137]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
np.tile(a, 3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [139]:
np.tile(a, (4, 3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [140]:
e1 = np.zeros((3 ,3))
e1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [148]:
e2 = np.ones((3, 2))
e2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [155]:
np.hstack([e1, e2])

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [156]:
e3 = np.arange(10, 151, 10)
e3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [157]:
e4 = e3.reshape(3, 5)
e4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [161]:
e5 = np.hstack([e1, e2])
e4 = e3.reshape(3, 5)
e6 = np.vstack([e5, e4])

In [163]:
np.tile(e6, (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [164]:
e1 = np.zeros((3 ,3))
e2 = np.ones((3, 2))
e3 = np.arange(10, 151, 10)
e4 = e3.reshape(3, 5)
e5 = np.hstack([e1, e2])
e4 = e3.reshape(3, 5)
e6 = np.vstack([e5, e4])

np.tile(e6, (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [173]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                    [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                    [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                    [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                    [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [174]:
practice.max()

9.0

In [175]:
practice.sum(axis=0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [176]:
practice.max(axis=0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [179]:
practice.mean(axis=1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [180]:
practice.min(axis=1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [181]:
a= np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [182]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [205]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])

In [206]:
eng = np.argsort(scores[1]) 

In [208]:
print(scores[:, [eng]])

[[[  1   4   2   3]]

 [[ 46  71  99 100]]

 [[ 81 100  59  90]]]


In [209]:
np.random.seed(0)

In [210]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [211]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [212]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [217]:
np.random.seed(0)
coin = np.random.randint(0, 2, 100)
coin

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [218]:
np.mean(coin)

0.56

In [219]:
coin.sum() / len(coin)

0.56

In [223]:
np.random.seed(0)
dice = np.random.randint(1, 7, 100)
dice

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2, 6, 1,
       2, 5, 4, 1, 4, 6, 1, 3, 4, 1, 2, 4, 6, 4, 4, 1, 2, 2, 2, 1, 3, 5,
       4, 4, 3, 5, 3, 1, 1, 5, 6, 6, 1, 5, 2, 5, 2, 3, 3, 1, 2, 2, 2, 2,
       4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5, 5, 5, 4, 5, 5, 5, 1, 5, 4,
       3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1])

In [224]:
dice.sum() / len(dice)

3.42