In [1]:
import numpy as np

np.random.seed(0)
dice = np.random.randint(1, 7, 100)
sum(dice) / len(dice)

3.42

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [3]:
d1 = np.arange(1, 10)
d1 * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
zero = np.zeros(11)
zero[4]=1
print(zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [5]:
c = np.arange(50)
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [6]:
d = np.zeros((3, 3, 3), dtype="U10")
d

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [7]:
np.full((3, 3, 3), 'playdata', dtype="U8")

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [8]:
e = np.arange(2, 41, 2)
e.reshape(2, 2, 5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.seed(0)
f = np.random.randint(0, 2, 9)
f.astype("bool").reshape(3, 3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [11]:
np.random.seed(0)
f = np.random.randint(0, 2, (3, 3))
f.astype("?")

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [12]:
np.random.seed(0)
g = np.random.rand(10) * 10
g.astype("int")

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [13]:
h = np.ones((10, 10))
h[1:-1, 1:-1] = 0
i = h-1
i[1:-1, 1:-1] = 1
i

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
h = np.ones((10, 10))
h[0:, 0] = 0
h[0:, -1] = 0
h[0, 0:] = 0
h[-1, 0:] = 0
h

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
z = np.ones((10, 10))
z[:, [0, -1]] = 0
z[[0, -1], :] = 0
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
j = np.ones((8, 8))
j[1::2, ::2] = 0
j[::2, 1::2] = 0
print(j)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [17]:
k = np.array([[1, 0], [0, 1]])
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.tile(np.eye(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [19]:
l = np.arange(0, 11)
num = np.array([True if 3 < l < 7 else False for l in range(0, 11)])
m = l[num] * -1 
l[4:7] = m
print(l)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [20]:
l = np.arange(11)
l[(3 < l) & (7 > l)] *= -1
print(l)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [21]:
n = np.arange(3, 100, 3)
sum(n)

1683

In [22]:
np.linspace(0.1, 0.9, 9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [23]:


lotto = np.random.choice(46, 6, False)
sorted(lotto)


[6, 29, 33, 34, 43, 45]

In [24]:
while True:
    try:
        count = int(input("로또 몇개 드릴까여?"))
        if count <= 0 :
            raise Error
        numbers = np.arange(1, 46)
        lottos = [np.sort(np.random.choice(numbers, 6, replace=False)) for _ in range(count)]
        display(lottos)
        break
    except:
        print("자연수만 입력해주세요.")

로또 몇개 드릴까여? 1


[array([ 3, 18, 20, 24, 27, 37])]

In [25]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])

t = resp_time > 200
len(resp_time[t])

8

In [26]:
(resp_time > 200).sum()

8

In [27]:
print(np.percentile(resp_time, 0))
print(np.percentile(resp_time, 25))
print(np.percentile(resp_time, 50))
print(np.percentile(resp_time, 75))
print(np.percentile(resp_time, 100))

4.0
71.5
131.0
175.5
218.0


In [28]:
for i, v in enumerate(range(25, 76, 25)):
    print(f'{i + 1}분위 {v}%) 값: {np.percentile(resp_time, v)}ms')

1분위 25%) 값: 71.5ms
2분위 50%) 값: 131.0ms
3분위 75%) 값: 175.5ms


In [29]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
q = np.bincount(result, minlength = 3)

In [30]:
import numpy as np
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
count = np.bincount(result, minlength = 3)
winner_index = count.argmax()
print(f'{p[winner_index]}가 {count[winner_index]}표로 반장으로 선출되었습니다.')

뽀로로가 81표로 반장으로 선출되었습니다.
